module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.interface.ts',
    '!**/*.module.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  roots: ['<rootDir>', '<rootDir>/../test'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@config/(.*)$': '<rootDir>/config/$1',
    '^@prisma/(.*)$': '<rootDir>/prisma/$1',
    '^@auth/(.*)$': '<rootDir>/auth/$1',
    '^@users/(.*)$': '<rootDir>/users/$1',
    '^@stores/(.*)$': '<rootDir>/stores/$1',
    '^@regions/(.*)$': '<rootDir>/regions/$1',
    '^@tasks/(.*)$': '<rootDir>/tasks/$1',
    '^@checklists/(.*)$': '<rootDir>/checklists/$1',
    '^@incidents/(.*)$': '<rootDir>/incidents/$1',
    '^@audits/(.*)$': '<rootDir>/audits/$1',
    '^@notifications/(.*)$': '<rootDir>/notifications/$1',
    '^@messages/(.*)$': '<rootDir>/messages/$1',
    '^@websocket/(.*)$': '<rootDir>/websocket/$1',
  },
};
