/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UppgifterRouteImport } from './routes/uppgifter'
import { Route as TestpanelRouteImport } from './routes/testpanel'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as RapporterRouteImport } from './routes/rapporter'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as MotenRouteImport } from './routes/moten'
import { Route as MallarRouteImport } from './routes/mallar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KundrundaRouteImport } from './routes/kundrunda'
import { Route as InstallningarRouteImport } from './routes/installningar'
import { Route as AvvikelserRouteImport } from './routes/avvikelser'
import { Route as IndexRouteImport } from './routes/index'

const UppgifterRoute = UppgifterRouteImport.update({
  id: '/uppgifter',
  path: '/uppgifter',
  getParentRoute: () => rootRouteImport,
} as any)
const TestpanelRoute = TestpanelRouteImport.update({
  id: '/testpanel',
  path: '/testpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const RapporterRoute = RapporterRouteImport.update({
  id: '/rapporter',
  path: '/rapporter',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const MotenRoute = MotenRouteImport.update({
  id: '/moten',
  path: '/moten',
  getParentRoute: () => rootRouteImport,
} as any)
const MallarRoute = MallarRouteImport.update({
  id: '/mallar',
  path: '/mallar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KundrundaRoute = KundrundaRouteImport.update({
  id: '/kundrunda',
  path: '/kundrunda',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallningarRoute = InstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => rootRouteImport,
} as any)
const AvvikelserRoute = AvvikelserRouteImport.update({
  id: '/avvikelser',
  path: '/avvikelser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avvikelser': typeof AvvikelserRoute
  '/installningar': typeof InstallningarRoute
  '/kundrunda': typeof KundrundaRoute
  '/login': typeof LoginRoute
  '/mallar': typeof MallarRoute
  '/moten': typeof MotenRoute
  '/personal': typeof PersonalRoute
  '/rapporter': typeof RapporterRoute
  '/schema': typeof SchemaRoute
  '/testpanel': typeof TestpanelRoute
  '/uppgifter': typeof UppgifterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avvikelser': typeof AvvikelserRoute
  '/installningar': typeof InstallningarRoute
  '/kundrunda': typeof KundrundaRoute
  '/login': typeof LoginRoute
  '/mallar': typeof MallarRoute
  '/moten': typeof MotenRoute
  '/personal': typeof PersonalRoute
  '/rapporter': typeof RapporterRoute
  '/schema': typeof SchemaRoute
  '/testpanel': typeof TestpanelRoute
  '/uppgifter': typeof UppgifterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avvikelser': typeof AvvikelserRoute
  '/installningar': typeof InstallningarRoute
  '/kundrunda': typeof KundrundaRoute
  '/login': typeof LoginRoute
  '/mallar': typeof MallarRoute
  '/moten': typeof MotenRoute
  '/personal': typeof PersonalRoute
  '/rapporter': typeof RapporterRoute
  '/schema': typeof SchemaRoute
  '/testpanel': typeof TestpanelRoute
  '/uppgifter': typeof UppgifterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avvikelser'
    | '/installningar'
    | '/kundrunda'
    | '/login'
    | '/mallar'
    | '/moten'
    | '/personal'
    | '/rapporter'
    | '/schema'
    | '/testpanel'
    | '/uppgifter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avvikelser'
    | '/installningar'
    | '/kundrunda'
    | '/login'
    | '/mallar'
    | '/moten'
    | '/personal'
    | '/rapporter'
    | '/schema'
    | '/testpanel'
    | '/uppgifter'
  id:
    | '__root__'
    | '/'
    | '/avvikelser'
    | '/installningar'
    | '/kundrunda'
    | '/login'
    | '/mallar'
    | '/moten'
    | '/personal'
    | '/rapporter'
    | '/schema'
    | '/testpanel'
    | '/uppgifter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvvikelserRoute: typeof AvvikelserRoute
  InstallningarRoute: typeof InstallningarRoute
  KundrundaRoute: typeof KundrundaRoute
  LoginRoute: typeof LoginRoute
  MallarRoute: typeof MallarRoute
  MotenRoute: typeof MotenRoute
  PersonalRoute: typeof PersonalRoute
  RapporterRoute: typeof RapporterRoute
  SchemaRoute: typeof SchemaRoute
  TestpanelRoute: typeof TestpanelRoute
  UppgifterRoute: typeof UppgifterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uppgifter': {
      id: '/uppgifter'
      path: '/uppgifter'
      fullPath: '/uppgifter'
      preLoaderRoute: typeof UppgifterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testpanel': {
      id: '/testpanel'
      path: '/testpanel'
      fullPath: '/testpanel'
      preLoaderRoute: typeof TestpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapporter': {
      id: '/rapporter'
      path: '/rapporter'
      fullPath: '/rapporter'
      preLoaderRoute: typeof RapporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moten': {
      id: '/moten'
      path: '/moten'
      fullPath: '/moten'
      preLoaderRoute: typeof MotenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mallar': {
      id: '/mallar'
      path: '/mallar'
      fullPath: '/mallar'
      preLoaderRoute: typeof MallarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundrunda': {
      id: '/kundrunda'
      path: '/kundrunda'
      fullPath: '/kundrunda'
      preLoaderRoute: typeof KundrundaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installningar': {
      id: '/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof InstallningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avvikelser': {
      id: '/avvikelser'
      path: '/avvikelser'
      fullPath: '/avvikelser'
      preLoaderRoute: typeof AvvikelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvvikelserRoute: AvvikelserRoute,
  InstallningarRoute: InstallningarRoute,
  KundrundaRoute: KundrundaRoute,
  LoginRoute: LoginRoute,
  MallarRoute: MallarRoute,
  MotenRoute: MotenRoute,
  PersonalRoute: PersonalRoute,
  RapporterRoute: RapporterRoute,
  SchemaRoute: SchemaRoute,
  TestpanelRoute: TestpanelRoute,
  UppgifterRoute: UppgifterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
