/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UppgifterRouteImport } from './routes/uppgifter'
import { Route as StyrtavlorRouteImport } from './routes/styrtavlor'
import { Route as RevisionerRouteImport } from './routes/revisioner'
import { Route as RapporterRouteImport } from './routes/rapporter'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KommunikationRouteImport } from './routes/kommunikation'
import { Route as InstallningarRouteImport } from './routes/installningar'
import { Route as ButikerRouteImport } from './routes/butiker'
import { Route as AvvikelserRouteImport } from './routes/avvikelser'
import { Route as IndexRouteImport } from './routes/index'

const UppgifterRoute = UppgifterRouteImport.update({
  id: '/uppgifter',
  path: '/uppgifter',
  getParentRoute: () => rootRouteImport,
} as any)
const StyrtavlorRoute = StyrtavlorRouteImport.update({
  id: '/styrtavlor',
  path: '/styrtavlor',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionerRoute = RevisionerRouteImport.update({
  id: '/revisioner',
  path: '/revisioner',
  getParentRoute: () => rootRouteImport,
} as any)
const RapporterRoute = RapporterRouteImport.update({
  id: '/rapporter',
  path: '/rapporter',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KommunikationRoute = KommunikationRouteImport.update({
  id: '/kommunikation',
  path: '/kommunikation',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallningarRoute = InstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => rootRouteImport,
} as any)
const ButikerRoute = ButikerRouteImport.update({
  id: '/butiker',
  path: '/butiker',
  getParentRoute: () => rootRouteImport,
} as any)
const AvvikelserRoute = AvvikelserRouteImport.update({
  id: '/avvikelser',
  path: '/avvikelser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avvikelser': typeof AvvikelserRoute
  '/butiker': typeof ButikerRoute
  '/installningar': typeof InstallningarRoute
  '/kommunikation': typeof KommunikationRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/rapporter': typeof RapporterRoute
  '/revisioner': typeof RevisionerRoute
  '/styrtavlor': typeof StyrtavlorRoute
  '/uppgifter': typeof UppgifterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avvikelser': typeof AvvikelserRoute
  '/butiker': typeof ButikerRoute
  '/installningar': typeof InstallningarRoute
  '/kommunikation': typeof KommunikationRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/rapporter': typeof RapporterRoute
  '/revisioner': typeof RevisionerRoute
  '/styrtavlor': typeof StyrtavlorRoute
  '/uppgifter': typeof UppgifterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avvikelser': typeof AvvikelserRoute
  '/butiker': typeof ButikerRoute
  '/installningar': typeof InstallningarRoute
  '/kommunikation': typeof KommunikationRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/rapporter': typeof RapporterRoute
  '/revisioner': typeof RevisionerRoute
  '/styrtavlor': typeof StyrtavlorRoute
  '/uppgifter': typeof UppgifterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avvikelser'
    | '/butiker'
    | '/installningar'
    | '/kommunikation'
    | '/login'
    | '/personal'
    | '/rapporter'
    | '/revisioner'
    | '/styrtavlor'
    | '/uppgifter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avvikelser'
    | '/butiker'
    | '/installningar'
    | '/kommunikation'
    | '/login'
    | '/personal'
    | '/rapporter'
    | '/revisioner'
    | '/styrtavlor'
    | '/uppgifter'
  id:
    | '__root__'
    | '/'
    | '/avvikelser'
    | '/butiker'
    | '/installningar'
    | '/kommunikation'
    | '/login'
    | '/personal'
    | '/rapporter'
    | '/revisioner'
    | '/styrtavlor'
    | '/uppgifter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvvikelserRoute: typeof AvvikelserRoute
  ButikerRoute: typeof ButikerRoute
  InstallningarRoute: typeof InstallningarRoute
  KommunikationRoute: typeof KommunikationRoute
  LoginRoute: typeof LoginRoute
  PersonalRoute: typeof PersonalRoute
  RapporterRoute: typeof RapporterRoute
  RevisionerRoute: typeof RevisionerRoute
  StyrtavlorRoute: typeof StyrtavlorRoute
  UppgifterRoute: typeof UppgifterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uppgifter': {
      id: '/uppgifter'
      path: '/uppgifter'
      fullPath: '/uppgifter'
      preLoaderRoute: typeof UppgifterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styrtavlor': {
      id: '/styrtavlor'
      path: '/styrtavlor'
      fullPath: '/styrtavlor'
      preLoaderRoute: typeof StyrtavlorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisioner': {
      id: '/revisioner'
      path: '/revisioner'
      fullPath: '/revisioner'
      preLoaderRoute: typeof RevisionerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapporter': {
      id: '/rapporter'
      path: '/rapporter'
      fullPath: '/rapporter'
      preLoaderRoute: typeof RapporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommunikation': {
      id: '/kommunikation'
      path: '/kommunikation'
      fullPath: '/kommunikation'
      preLoaderRoute: typeof KommunikationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installningar': {
      id: '/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof InstallningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/butiker': {
      id: '/butiker'
      path: '/butiker'
      fullPath: '/butiker'
      preLoaderRoute: typeof ButikerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avvikelser': {
      id: '/avvikelser'
      path: '/avvikelser'
      fullPath: '/avvikelser'
      preLoaderRoute: typeof AvvikelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvvikelserRoute: AvvikelserRoute,
  ButikerRoute: ButikerRoute,
  InstallningarRoute: InstallningarRoute,
  KommunikationRoute: KommunikationRoute,
  LoginRoute: LoginRoute,
  PersonalRoute: PersonalRoute,
  RapporterRoute: RapporterRoute,
  RevisionerRoute: RevisionerRoute,
  StyrtavlorRoute: StyrtavlorRoute,
  UppgifterRoute: UppgifterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
